; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.20"

; Modules
projects[admin_menu][version] = "1.6"

projects[ajax][version] = "1.14"

projects[backup_migrate][version] = "2.4"

projects[better_messages][version] = "1.13"

projects[boost][version] = "1.x-dev"

projects[bueditor][version] = "2.2"

projects[css_gzip][version] = "1.3"

projects[csstidy][version] = "1.3"

projects[cvs_deploy][version] = "1.1"

projects[db_maintenance][version] = "1.3"

;projects[gallery_assist][version] = "1.x-dev"

;projects[gallery_assist_ic][version] = "1.2"

;projects[gallery_assist_lightboxes][version] = "1.4"

projects[globalredirect][version] = "1.2"

projects[google_analytics][version] = "3.3"

projects[i18n][version] = "1.9"

projects[i18nlogo][version] = "1.x-dev"

projects[image_resize_filter][version] = "1.12"

projects[imageapi][version] = "1.9"

projects[imagecache][version] = "2.0-beta10"

projects[javascript_aggregator][version] = "1.5"

projects[jcarousellite][version] = "2.0-beta6"

projects[jquery_plugin][version] = "1.10"

projects[jquery_update][version] = "1.1"

projects[jquery_ui][version] = "1.4"

projects[languageicons][version] = "2.0"

projects[lightbox2][version] = "1.11"

projects[nodewords][version] = "1.x-dev"

projects[page_title][version] = "2.3"

projects[path_redirect][version] = "1.0-rc2"

projects[pngfix][version] = "1.0"

projects[security_review][version] = "1.0"

projects[seo_checklist][version] = "3.0"

projects[site_verify][version] = "1.0"

projects[skinr][version] = "1.6"

projects[tcontact][version] = "1.2"

projects[token][version] = "1.15"

projects[translation404][version] = "1.2"

projects[translation_overview][version] = "2.4"

projects[transliteration][version] = "3.0"

projects[vertical_tabs][version] = "1.0-rc1"

projects[xmlsitemap][version] = "2.0-beta2"

projects[cck][version] = "2.9"

projects[imagefield][version] =  "3.9"

projects[filefield][version] =  "3.9"

projects[mimedetect][version] =  "1.3"

projects[galleryformatter][version] = "1.0-rc3"

; Themes
projects[fusion][version] = "1.0-rc1"

; Custom Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[contactajax][download][type] = "git"
projects[contactajax][download][url] = "git://gitorious.org/katyasart/contactajax.git"
projects[contactajax][type] = "module"
projects[contactajax][subdir] = "custom_modules"

; Custom Themes
projects[fusion_studio][download][type] = "git"
projects[fusion_studio][download][url] = "git://gitorious.org/katyasart/fusion_studio.git"
projects[fusion_studio][type] = "theme"
projects[fusion_studio][branch] = "6.x-1.x"
projects[fusion_studio][subdir] = "custom_themes"

; Libraries

libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][destination] = "modules/jquery_ui"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery.ui-1.6.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"